version: "3.3"

services:
    keycloak: 
        container_name: keycloak
        image: andrades/cloud/keycloak:latest
        command: start --optimized
        user: root
        hostname: auth.andrades.cloud
        build:
            context: .
            dockerfile: Dockerfile
        depends_on: 
          - "postgres" 
        environment:
          KC_DB_URL: jdbc:postgresql://postgres/keycloak
          KC_DB_USERNAME: keycloak
          KC_DB_PASSWORD: keycloak
          KEYCLOAK_ADMIN: localhost
          KEYCLOAK_ADMIN_PASSWORD: changeme
        volumes:
          - /root/certs/fullchain.pem:/opt/keycloak/server.crt.pem
          - /root/certs/key.pem:/opt/keycloak/server.key.pem
        ports: 
          - 80:80
          - 443:443
        networks: 
          - keycloak-network 
    postgres:
        container_name: 'postgres'
        image: postgres
        restart: unless-stopped
        healthcheck:
          test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
          timeout: 45s
          interval: 10s
          retries: 10        
        environment:
          POSTGRES_PASSWORD: postgres
          APP_DB_USER: keycloak
          APP_DB_PASS: keycloak
          APP_DB_NAME: keycloak
        volumes:
            - /root/docker/data/postgres:/var/lib/postgresql/data:rw
            - ./database:/docker-entrypoint-initdb.d/
        networks:
            - keycloak-network
      
    pgadmin:
        container_name: 'pgadmin'
        image: dpage/pgadmin4
        restart: unless-stopped
        user: root
        environment:
          PGADMIN_DEFAULT_EMAIL: "postgres@example.com"
          PGADMIN_DEFAULT_PASSWORD: postgres
        depends_on:
            - postgres
        networks:
            - keycloak-network
        volumes:
            - /root/docker/data/pgadmin:/var/lib/pgadmin:rw
networks:
  keycloak-network:
    driver: bridge




