version: "3.9"
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    restart: unless-stopped

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    links:
      - keycloak
    networks:
      - keycloak-network
    ##  USE THIS CASE NEEDED TO ATTACH TO CONTAINER
    #entrypoint: /bin/bash
    #stdin_open: true # docker run -i
    #tty: true # docker run -t
  keycloak:
    container_name: keycloak
    image: andrades/cloud/keycloak:proxied
    command: start --proxy passthrough
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
    environment:
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: localhost
      KEYCLOAK_ADMIN_PASSWORD: changeme
    networks:
      - keycloak-network
  postgres:
    container_name: 'postgres'
    image: postgres
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "root"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_PASSWORD: postgres
      APP_DB_USER: keycloak
      APP_DB_PASS: keycloak
      APP_DB_NAME: keycloak
    volumes:
      - /root/docker/data/postgres:/var/lib/postgresql/data:rw
      - ./database:/docker-entrypoint-initdb.d/
    networks:
      - keycloak-network

  pgadmin:
    container_name: 'pgadmin'
    image: dpage/pgadmin4
    restart: unless-stopped
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@example.com"
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - keycloak-network
    volumes:
      - /root/docker/data/pgadmin:/var/lib/pgadmin:rw
networks:
  keycloak-network:
    driver: bridge
